### PR TITLE
remove unneeded value for server inserter

### PR DESCRIPTION
**Pull request by woglinde**

### CODE REVIEW

**Comment by zecke** [comment]
Why? The port is needed to say where the system should listen for a connection.

**Comment by woglinde** [comment]
Because when I do a GET the port is not visible in the json response. I removed it from the IT-tests for PUT too and the REST server did not complain.

**Comment by zecke** [comment]
Then please update your image and test. Make sure that not passing the port does render a 5XX (or at least not a 200) and verify it is being returned.

**Comment by zecke** [comment]
Then leave the port in.

**Pull request closed without merging**
